# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Marco Gramaglia Personal WebPage
email: mgramagl@it.uc3m.es
description: >- # this means to ignore newlines until "baseurl:"
  Marco Gramaglia Persona Webpage. Professor at Universidad Carlos III de Madrid
twitter_username: mgramagl
github_username: mgramagl
minimal_mistakes_skin: default
search: true
#url: https://www.it.uc3m.es/mgramagl
# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: ES

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Marco Gramaglia"
  avatar : "/assets/images/photo.jpg"
  bio    : "I am a Professor at the Telematics Engineering Department, Universidad Carlos III de Madrid."
  links:
    - label: "Phone: "
      icon: "fas fa-fw fa-phone"
      url: "tel:0034916248747"
    - label: "+34 91684 8747"
      icon: "fa-fw"
      url: "#"
    - label: "Address"
      icon: "fas fa-fw fa-map-pin"
      url: "https://maps.app.goo.gl/ZZnxtLN9Srt41bQ37"
    - label: "Avenida Universidad 30 </br> 28911, Leganes </br> Madrid, Spain"
      icon: "fa-fw"
      url: "#"
    - label: "Office"
      icon: "fas fa-fw fa-building"
      url: "#"
    - label: "4.1.A12"
      icon: "fa-fw"
      url: "#"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.mgramaglia.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mgramagl"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mgramagl"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=0c7H9bQAAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/marco-gramaglia-04831855/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/mgramagl"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/mgramagl"
    - label: "Google Scholar"
      icon: "fab fa-fw fa-google"
      url: "https://scholar.google.com/citations?user=0c7H9bQAAAAJ&hl=en"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/marco-gramaglia-04831855/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
